// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gisymyvgrldpfwyrppgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpc3lteXZncmxkcGZ3eXJwcGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNzc2MDYsImV4cCI6MjA1MTc1MzYwNn0.c4jye8cQNsI_re-SfhhZ6ZDinIR4WdGyrbKKApQNXOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);